#%RAML 1.0 Trait
usage: To enforce client_id identification.
headers:
  client_id:
    description: To authenticate System API
    type: string
    required: true
  client_secret:
    description: To authenticate System API
    type: string
    required: true